backend:
  name: github
  repo: allforabit/herb-and-bloom

media_folder: static/assets
public_folder: assets

collections:
  - name: gallery_item
    label: Gallery item
    folder: gallery
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: image, label: Body, widget: image }
